# Generated by Django 3.0.8 on 2021-01-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
