# Generated by Django 3.0.8 on 2021-01-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20210113_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidityentry',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='pressureentry',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='temperatureentry',
            name='sensor',
        ),
    ]
