# Generated by Django 3.0.8 on 2021-01-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210113_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidityentry',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressureentry',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatureentry',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
            preserve_default=False,
        ),
    ]
