# Generated by Django 3.0.8 on 2021-01-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20210114_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidityentry',
            name='value',
        ),
        migrations.RemoveField(
            model_name='pressureentry',
            name='value',
        ),
        migrations.RemoveField(
            model_name='temperatureentry',
            name='value',
        ),
    ]
