# Generated by Django 3.0.8 on 2021-01-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20210114_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressureentry',
            old_name='Presuure',
            new_name='pressure',
        ),
    ]
