import App from './components/app'
import Login from './components/login'
import NavPanel from './components/nav'
import theme from './components/theme'
import Example from './components/chart'
import Sticker from './components/sticker'
import SiderDemo from './components/temp'